title: Freelance Content Writer
tagline: SEO, blogs, social media and marketing campaigns.
theme: minima
author:
  name: Tatiana 
  email: tashukwork@gmail.com
description: Creating content for your website, blog, social media and marketing campaigns.
excerpt_separator: <!--more-->
