title: Freelance Content Writer
tagline: Creating content for your website, blog, social media and marketing campaigns.
theme: minima
author:
  name: Tatiana 
  email: tashukwrite@yahoo.com
description: Creating content for your website, blog, social media and marketing campaigns.